export const ROUTE_NAMES = {
  AUTH: {
    SIGN_IN: "SignIn",
    SIGN_UP: "SignUp",
    FORGET_PASSWORD: "ForgetPassword",
  },
  GUEST: {
    HOME: "GuestHome",
    PROMOTION: "GuestPromotion",
    CHALLENGE: "GuestChallengeIntroduction",
    ABOUT: "GuestAbout",
  },
  USER: {
    HOME: "UserHome",
    PROMOTION: "UserPromotion",
    CHALLENGE: "UserChanllenge",
    ABOUT: "UserAbout",
    PROFILE: "UserProfile",
    EDIT_PROFILE: "EditUserProfile",
    CHANGE_PASSWORD: "ChangeUserPassword",
    CART: "UserCart",
  },
  STAFF: {
    HOME: "StaffHome",
    PROMOTION: "StaffPromotion",
    CHALLENGE: "StaffChallenge",
    ABOUT: "StaffAbout",
    PROFILE: "StaffProfile",
    EDIT_PROFILE: "EditStaffProfile",
    CHANGE_PASSWORD: "ChangeStaffPassword",
    CART: "StaffCart",
    ORDER_MANAGEMENT: "StaffOrderDetail",
  },
  ADMIN: {
    HOME: "AdminHome",
    CUSTOMER_MANAGEMENT: "CustomerManagement",
    STAFF_MANAGEMENT: "StaffManagement",
    CATEGORY_MANAGEMENT: "CategoryManagement",
    PRODUCT_MANAGEMENT: "ProductManagement",
    PROMOTION_CATEGORY_MANAGEMENT: "PromotionByCategoryManagement",
    PROMOTION_CATEGORY_ADD: "PromotionByCategoryAdd",
    PROMOTION_PRODUCT_MANAGEMENT: "PromotionByProductManagement",
  },
} as const;
