export const ROUTE_NAMES = {
  AUTH: {
    SIGN_IN: "SignIn",
    SIGN_UP: "SignUp",
    FORGET_PASSWORD: "ForgetPassword",
  },
  GUEST: {
    HOME: "GuestHome",
    CATEGORY_DETAIL: "GuestCategoryDetail",
    PRODUCT_DETAIL: "GuestProductDetail",
    ALL_PRODUCT_REVIEWS: "GuestAllProductReivews",
    PROMOTION: "GuestPromotion",
    CHALLENGE: "GuestChallengeIntroduction",
    ABOUT: "GuestAbout",
  },
  USER: {
    HOME: "UserHome",
    CATEGORY_DETAIL: "UserCategoryDetail",
    PRODUCT_DETAIL: "UserProductDetail",
    PROMOTION: "UserPromotion",
    CHALLENGE: "UserChanllenge",
    ABOUT: "UserAbout",
    PROFILE: "UserProfile",
    EDIT_PROFILE: "EditUserProfile",
    CHANGE_PASSWORD: "ChangeUserPassword",
    CART: "UserCart",
    ORDER_TRACKING: "UserOrderTracking",
    ORDER_HISTORY: "UserOrderHistory",
    PRODUCT_REVIEW: "UserProductReview",
    ALL_PRODUCT_REVIEWS: "UserAllProductReivews",
  },
  STAFF: {
    HOME: "StaffHome",
    CATEGORY_DETAIL: "StaffCategoryDetail",
    PRODUCT_DETAIL: "StaffProductDetail",
    PROMOTION: "StaffPromotion",
    CHALLENGE: "StaffChallenge",
    ABOUT: "StaffAbout",
    PROFILE: "StaffProfile",
    EDIT_PROFILE: "EditStaffProfile",
    CHANGE_PASSWORD: "ChangeStaffPassword",
    CART: "StaffCart",
    ORDER_TRACKING: "StaffOrderTracking",
    ORDER_HISTORY: "StaffOrderHistory",
    PRODUCT_REVIEW: "StaffProductReview",
    ALL_PRODUCT_REVIEWS: "StaffAllProductReivews",
    ORDER_MANAGEMENT: "StaffOrderDetail",
  },
  ADMIN: {
    HOME: "AdminHome",
    CATEGORY_DETAIL: "AdminCategoryDetail",
    PRODUCT_DETAIL: "AdminProductDetail",
    CUSTOMER_MANAGEMENT: "CustomerManagement",
    STAFF_MANAGEMENT: "StaffManagement",
    CATEGORY_MANAGEMENT: "CategoryManagement",
    PRODUCT_MANAGEMENT: "ProductManagement",
    PROMOTION_CATEGORY_MANAGEMENT: "PromotionByCategoryManagement",
    PROMOTION_CATEGORY_ADD: "PromotionByCategoryAdd",
    PROMOTION_PRODUCT_MANAGEMENT: "PromotionByProductManagement",
    PROMOTION_PRODUCT_ADD: "PromotionByProductAdd",
    PROMOTION_ORDER_MANAGEMENT: "PromotionOrderManagement",
    PROMOTION_ORDER_ADD: "PromotionOrderAdd",
  },
} as const;
